### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [agateau/pixelwheels#17] opened 2018-05-25 09:07 UTC
Hi,

Since this app is free software, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

Just to let you know, there is a request for your app [here](https://gitlab.com/fdroid/rfp/issues/587).

**Comment by Poussinou** [comment] 2018-05-28 10:18
Ok, sounds good. Do not hesitate to come on Gitlab to talk about this ;)

**Comment by Symbian9** [comment] 2018-07-20 20:22
> I definitely would like to see Pixel Wheels on F-Droid, but as it has been pointed out in the request for inclusion, the fact that I use Aseprite makes it complicated: while Aseprite source code is available, the license does not allow redistributing binaries. This means that F-Droid would need to either build Aseprite itself (doable but annoying) or get an Aseprite license (unlikely).

As you know, *Aseprite* up to version `1.17` was licensed under GNU GPL, but later it switched to EULA... ([spoiler!](https://news.ycombinator.com/item?id=17343864))

Anyway, latest *Aseprite* `v1.17` was forked under GNU GPL and renamed to *LibreSprite*!

- https://github.com/LibreSprite/LibreSprite

@agateau, so, is it possible switch to use LibreSprite for Pixel Wheels?

**Comment by agateau** [comment] 2018-09-01 18:14
I am not going to personally switch to LibreSprite, but I committed changes to master to make it possible to use it instead of Aseprite. It looks like it's working here.

**Comment by Symbian9** [comment] 2018-09-02 13:02
>  I committed changes to master to make it possible to use *LibreSprite* instead of *Aseprite*. It looks like it's working here.

Great!

@IzzySoft, can you check, please, is *PixelWheels* ready for submitting to F-Droid now?

**Comment by IzzySoft** [comment] 2018-09-02 13:37
@Symbian9 I've [updated the issue over there](https://gitlab.com/fdroid/rfp/issues/587#note_98329172) and triggered another bot run. I cannot tell for sure, and as I'm leaving for vacation cannot check the next few days. Pinged a maintainer to check.

**Comment by Symbian9** [comment] 2018-09-09 21:40
> I cannot tell for sure, and as I'm leaving for vacation cannot check the next few days. Pinged a maintainer to check.

@IzzySoft, as *Pixel Wheels* `v0.10.0` now could be built using *LibreSprite* (that mean that there no any dependency to *Aceprite* anymore), so are there any issues that still prevent adding *Pixel Wheels* into *F-Droid* repo?

**Comment by IzzySoft** [comment] 2018-09-18 15:33
@Symbian9 just left a note over there which hopefully will be picked up soon. The dev I pinged last time is on vacation now, but with a little luck someone takes over.

**Comment by Rudloff** [comment] 2019-01-31 21:36
I managed to build the app using the aseprite package from Debian (which should not have any licensing issue).
However, when trying to build it on our build server VM, it fails:
```
aseprite --batch --split-layers --trim sprites/hud/hud-pie-buttons.ase \
	--filename-format '{path}/hud-{layer}.{extension}' --save-as sprites/hud/whatever.png
Cannot initialize Allegro library: 
Cannot initialize Allegro library: Makefile:21: recipe for target '../assets/sprites/hud-pause.png' failed
```
Could it be because the server is headless?

**Comment by agateau** [comment] 2019-02-10 15:30
That is likely the problem indeed. If it's possible on the server, maybe you can run the command through `xvfb-run`?

**Comment by agateau** [comment] 2019-02-10 15:30
(Delighted to hear you are working on this, btw!)

**Comment by Rudloff** [comment] 2019-02-11 10:51
Thanks for the help! `assets` works with `xvfb-run`, but `mapscreenshotgenerator` crashes:
```
DEBUG: buildserver > + xvfb-run -a make -C .. mapscreenshotgenerator
DEBUG: buildserver > make: Entering directory '/home/vagrant/build/com.agateau.tinywheels.android'
DEBUG: buildserver > java -cp /home/vagrant/build/com.agateau.tinywheels.android/tools/build/libs/tools-1.0.jar com.agateau.pixelwheels.tools.MapScreenshotGenerator
DEBUG: buildserver > Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
DEBUG: buildserver > 	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:591)
DEBUG: buildserver > 	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
DEBUG: buildserver > Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
DEBUG: buildserver > 	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
DEBUG: buildserver > 	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
DEBUG: buildserver > 	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
DEBUG: buildserver > 	... 2 more
DEBUG: buildserver > make: Leaving directory '/home/vagrant/build/com.agateau.tinywheels.android'
```

This if my first time using xvfb so I am not sure if some settings could help work around that.

**Comment by agateau** [comment] 2019-02-23 16:21
(Sorry for the late answer :snail:) Looks like it fails because xvfb-run does not support OpenGL acceleration. You can try with these arguments:

`xvfb-run --auto-servernum --server-args -screen 0 1024x768x24 +extension GLX`

This is what I use in another project which also requires OpenGL.

**Comment by Rudloff** [comment] 2019-02-25 15:03
I tried `xvfb-run -a --server-args '-screen 0 1024x768x24 +extension GLX' make -C .. mapscreenshotgenerator` but I still get the same error :slightly_frowning_face: 
Running `glxinfo` with the same arguments works so I think OpenGL is available.

**Comment by agateau** [comment] 2019-03-16 09:32
Maybe it would be simpler if I published an archive of the produced assets with each release, so that F-Droid builders just have to combine them with the source tree to build the game?

**Comment by Rudloff** [comment] 2019-03-17 17:30
I guess it could be a solution, but I don't want to make the app harder to maintain for you.

**Comment by agateau** [comment] 2019-03-24 17:08
Actually I have a better idea: those screenshots do not look very good, I am going to replace them with custom icons :)

**Comment by Rudloff** [comment] 2019-03-26 21:49
OK, feel free to ping me when we can try building something :slightly_smiling_face:

**Comment by agateau** [comment] 2019-04-07 16:47
Finally found the time to work on this: current master now ships with hand-made map icons. It should make it easier for you.

**Comment by Rudloff** [comment] 2019-04-07 18:02
I confirm d4370a7fb53be00e735469787363b3fafc556256 now builds correctly in our VM.
Feel free to ping me when you tag a new release so I can publish it.

**Comment by agateau** [comment] 2019-04-14 16:48
Great news! Thanks!
Now I "just" have to make a new release :)

**Comment by agateau** [comment] 2019-08-14 06:40
Closing this now that the game is on F-Droid.

**Comment by licaon-kter** [comment] 2020-05-02 08:52
16 fails to build
```
Git fetch failed
detail begin

error: cannot lock ref 'refs/remotes/origin/dev': 'refs/remotes/origin/dev/simplify-camera' exists; cannot create 'refs/remotes/origin/dev' From https://github.com/agateau/pixelwheels

! [new branch]        dev        -> origin/dev  (unable to update local ref)
```

**Comment by agateau** [comment] 2020-05-03 08:23
> error: cannot lock ref 'refs/remotes/origin/dev': 'refs/remotes/origin/dev/simplify-camera' exists; cannot create 'refs/remotes/origin/dev' From https://github.com/agateau/pixelwheels
>
> ! [new branch]        dev        -> origin/dev  (unable to update local ref)

I think that error is caused by some branch renaming I made lately. There used to be `dev/$topic` topic branches and a `work` branch where I merge things before they go to `master` (which only accepts commits approved by CI), but this was inconsistent with my other projects where I use `wip/$topic` for topic branches and `dev` for the branch where I merge things before they go to `master`.

Since Git does not support having a branch called `foo` and another called `foo/bar` this causes a problem on F-Droid build server: git refuses to pull the `dev` branch because it has a local copy of the `dev/simplify-camera` branch. I think manually deleting the `dev/*` local branches or simply recloning the git repository should fix it.

Sorry for the unexpected inconvenience. Let me know if you need more help.

**Closed** 2020-09-13 15:50 UTC
