### ISSUE TITLE
Can't see my mouse cursor or use arrow keys on menus

### ISSUE THREAD

**Issue by ebm539** [agateau/pixelwheels#29] opened 2019-08-20 09:00 UTC
Using the prebuilt binary (0.13.0) on i3wm on Arch Linux.

Running java as `java -jar pixelwheels.jar`

In game the keyboard is fine (can use arrow keys and space bar to drive the car and activate bonuses, haven't tested second player's controls)

**Comment by agateau** [comment] 2019-08-21 09:59
Indeed, I took a shortcut on desktop and just hide the mouse cursor at startup. I need to revisit that.

What is your problem with the arrow keys? they should let you navigate all the menu elements.

**Comment by ebm539** [comment] 2019-08-22 09:20
The menu system does not respond to the arrow keys - the selected element outline does not change, and pressing enter does nothing.

Pressing escape goes back to the previous menu however.

**Comment by agateau** [comment] 2019-08-23 05:22
Strange. I need to find a way to reproduce it. Which OS do you use?

**Comment by ebm539** [comment] 2019-08-24 02:57
I use Arch Linux.

I got the menu system to respond to the arrow keys - I had to _not_ have my user (on Linux) in the `input` group (I had added myself to the `input` group previously, I can't remember why)

**Comment by agateau** [comment] 2019-08-30 18:17
Nice catch, I wouldn't have thought of that! This looks like a bug in libgdx or in its lwjgl3 backend.

Now that Pixel Wheels has an auto-hiding mouse cursor I am closing this report.

**Closed** 2019-08-30 18:18 UTC
Labels: enhancement, waiting answer
