### ISSUE TITLE
Double rocket

### ISSUE THREAD

**Issue by Jakod21** [agateau/pixelwheels#59] opened 2019-10-14 10:33 UTC
I got two boxes at the same time and when I hit attack it sent two rockets. I suppose it is a bug?

**Comment by Jakod21** [comment] 2019-10-14 10:34
Also, 2Deuch appears as 2cv on the leaderboard.

**Comment by timakro** [comment] 2019-10-14 16:38
Can't reproduce. If you triggered the rockets immediately after picking up the boxes this might be #56.

**Comment by agateau** [comment] 2019-10-15 20:43
> Also, 2Deuch appears as 2cv on the leaderboard.

Indeed, this has been fixed.

**Comment by agateau** [comment] 2019-10-15 20:45
I agree with @timakro. Going to close this for now, assuming his fix address the issue. Please reopen if you can reproduce with 0.14.0 when it's out (hopefully by the end of the month).

**Closed by agateau** 2019-10-15 20:45 UTC

**Comment by Wilker-a** [comment] 2019-10-16 01:25
i think that they refer to picking another box while having the fire button pressed. by chance, another rocket appeared as the powerup. is that it?
