### ISSUE TITLE
Negative timing

### ISSUE THREAD

**Issue by Jakod21** [agateau/pixelwheels#60] opened 2019-10-14 15:55 UTC
![Screenshot_20191014-155109](https://user-images.githubusercontent.com/17675174/66765177-4074ff00-eea3-11e9-8f22-b60b4dbd437a.jpg)
The rocket AI seldom gets last place, I usually see the rocket in the middle of the road without moving, but this is unseen to me.

**Comment by Wilker-a** [comment] 2019-10-14 21:37
duplicate of #38 (closed) :3

**Closed** 2019-10-15 20:34 UTC
