### ISSUE TITLE
No game icon is shown on the Windows taskbar after opening the game

### ISSUE THREAD

**Issue by lukmarcus** [agateau/pixelwheels#347] opened 2023-05-15 23:32 UTC
## Describe the bug

No game icon is shown on the Windows taskbar after opening the game.

### How to reproduce

1. Open 'Pixel Wheels' game
2. Pay attention to the icon on the Windows taskbar.

### Expected behavior

The game icon is shown on the Windows taskbar after opening the game.

## Information about your build

Pixel Wheels version: 0.42.2

Binary origin:
- [x] itch.io
- [ ] Google Play
- [ ] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [ ] Android
- [x] Windows
- [ ] macOS
- [ ] Linux

OS version: Windows 10 x64

## Optional information

Screenshot:

![icon](https://github.com/agateau/pixelwheels/assets/1151664/b35a80de-4089-4870-a932-496166971fc3)

**Comment by agateau** [comment] 2023-06-13 13:52
Hi, I finally took the time to reboot on my Windows partition to try it out and... it works for me 😕:

![image](https://github.com/agateau/pixelwheels/assets/3575/390b4194-1154-4017-85bc-c6905fd143ee)

Is the icon always missing for you or is it an once-in-a-while bug?

**Comment by lukmarcus** [comment] 2023-06-19 17:31
> Hi, I finally took the time to reboot on my Windows partition to try it out and... it works for me 😕:
> 
> ![image](https://user-images.githubusercontent.com/3575/245497643-390b4194-1154-4017-85bc-c6905fd143ee.png)
> 
> Is the icon always missing for you or is it an once-in-a-while bug?

I'm sorry but I'm unable to reproduce this bug right now. I always try the same bug few times to be sure but I guess that was some kind of Windows thing.

**Comment by agateau** [comment] 2023-06-20 20:09
OK, closing it for now, then. Feel free to reopen if you can reproduce again!

**Closed by agateau** 2023-06-20 20:09 UTC
